services:
  backend:
    build: ./backend
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ensure DB is ready before backend starts
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/chatbot_db
    restart: unless-stopped

  frontend:
    build: ./frontend/chatbot
    container_name: chatbot_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/chatbot:/app
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: chatbot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - chatbot_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chatbot_data:
